FROM node:lts-alpine

WORKDIR /app

ARG node_env=production
ENV NODE_ENV $node_env

# Copy the build artifacts from the previous stage
ARG project
COPY  /dist/apps/$project .

RUN npm install --silent

CMD ["node", "main.js"]
